# Generated by Django 6.1 on 2026-09-25 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_slide'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='cars_in_stock',
            field=models.CharField(default='200+', max_length=50, verbose_name='Автомобилей в наличии'),
        ),
        migrations.AddField(
            model_name='settings',
            name='happy_clients',
            field=models.CharField(default='4 800', max_length=50, verbose_name='Довольных клиентов'),
        ),
        migrations.AddField(
            model_name='settings',
            name='years_on_market',
            field=models.CharField(default='15+', max_length=50, verbose_name='Лет на рынке'),
        ),
    ]
