# Generated by Django 6.1 on 2026-10-09 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название банка')),
                ('author', models.CharField(max_length=50, verbose_name='Имя пользователя')),
                ('number', models.IntegerField(verbose_name='номер счет')),
                ('money', models.IntegerField(verbose_name='Количество денег на балансе')),
            ],
            options={
                'verbose_name': 'Главная характеристика',
                'verbose_name_plural': 'Главные характеристики',
            },
        ),
    ]
