# Generated by Django 6.1 on 2026-09-15 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название сайта')),
                ('descrimption', models.TextField(verbose_name='описание')),
                ('logo', models.ImageField(upload_to='logo/')),
                ('phone', models.CharField(max_length=255, verbose_name='Телефонный номер')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта электронная')),
                ('address', models.CharField(max_length=250, verbose_name='Адрес')),
                ('locate_url', models.URLField(verbose_name='Ссылка адреса')),
            ],
            options={
                'verbose_name': 'Основная настройка',
            },
        ),
    ]
