# Generated by Django 6.1 on 2026-09-15 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': 'Основная настройка', 'verbose_name_plural': 'Основные настройки'},
        ),
    ]
