# Generated by Django 6.1 on 2026-09-18 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Numbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(verbose_name='Лет в небе')),
                ('destinations', models.IntegerField(verbose_name='направлений')),
                ('people', models.IntegerField(verbose_name='пассажиров в небе')),
                ('reis', models.IntegerField(verbose_name='Рейсов в небе')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннеры',
            },
        ),
    ]
