# Generated by Django 6.1 on 2026-09-18 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numbers',
            name='people',
            field=models.CharField(max_length=275, verbose_name='пассажиров в небе'),
        ),
    ]
