# Generated by Django 6.1 on 2026-09-22 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_numbers_people'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='descrimption',
            new_name='descriptions',
        ),
    ]
