# Generated by Django 6.1 on 2026-09-22 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_descrimption_settings_descriptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tour/', verbose_name='Изображение')),
                ('title', models.CharField(max_length=255, verbose_name='Название тура')),
                ('subtitle', models.CharField(max_length=255, verbose_name='Подзаголовок')),
                ('price', models.CharField(max_length=255, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Тур',
                'verbose_name_plural': 'Туры',
            },
        ),
    ]
