# Generated by Django 6.1 on 2026-09-04 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=120, verbose_name='Автор книги')),
                ('title', models.CharField(max_length=60, verbose_name='Название книги')),
                ('description', models.TextField(blank=True, default='Без описания', verbose_name='Описание книги')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена книги')),
                ('year', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='book_image/', verbose_name='Изображение книги')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
    ]
