# Generated by Django 6.1.1 on 2026-09-06 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=120, verbose_name='Режиссер фильма')),
                ('name', models.CharField(max_length=60, verbose_name='Название фильма')),
                ('actors', models.CharField(max_length=60, verbose_name='Главный герой фильма')),
                ('description', models.TextField(blank=True, default='Без описания', verbose_name='Описание фильма')),
                ('year', models.DateField(blank=True, null=True)),
                ('company', models.CharField(max_length=120, verbose_name='Комания фильма')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
            },
        ),
        migrations.DeleteModel(
            name='Books',
        ),
    ]
