# Generated by Django 6.1 on 2026-10-02 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='название товара')),
                ('description', models.TextField(blank=True, verbose_name='описание товара')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='цена')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='количество на складе')),
                ('is_available', models.BooleanField(default=True, verbose_name='в наличии ли товар')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата добавления')),
            ],
        ),
    ]
