;
; DelDrv.ini
;
; LastModified: 22-Aug-2005
;
[Setup]
GUID=%GUID_UNINSTALLER%
;-------------------------------------------------------------
; OPTIONAL
;-------------------------------------------------------------
; VisualStyle(Windows XP or later)
; This value cannot use righthand variable.
EnableVisualStyle=1

[LANGUAGES]
; 0000 ---- Neutral(Default)
0000=,SetupRes.ini,DelDrvRes.dll
