;
; StringTable(English)
;
; LastModified: 15-Mar-2007
;
[Strings]
REGION_DEFAULT=0
FILE_LICENSE_REGION0=License.txt
FILE_LICENSE_REGION1=License.txt
FILE_LICENSE_REGION2=License.txt
FILE_LICENSE_REGION3=License.txt
FILE_README_NAME0=Readme_UFRIILT.txt
FILE_README_NAME1=Readme_SG.txt
FILE_EXCLUSIVE_INF_ME=mf31cmp.inf
GUID_UNINSTALLER={900A29A0-52BA-4a78-8E6C-5F4F821397CE}
DIR_PROGRAMSHORTCUT=Canon\MF4010 Series
DIR_WIN9X=win98_me
DIR_WINNT5=win2k_vista
DIR_WINNT5_X64=Driver
DIR_DEVICE=\MF4010
NAME_PRODUCT=Драйверы MF
NAME_READMESHORTCUT=Файл Readme для серии MF4010
NAME_READMESHORTCUT0=Файл Readme для UFRII LT
NAME_READMESHORTCUT1=Файл Readme для ScanGear
NAME_OS_WIN9X=Windows 98/Me
NAME_OS_WINNT5=Windows 2000/XP/Vista
NAME_OS_WINNT5_X64=Windows XP(64-bit)
NAME_DELIMITER=", "
NAME_UNINSTALLER=Серия Canon MF4010
NAME_UNINSTALLERSHORTCUT=Удаление драйверов
NAME_USB=&USB-соединение
NAME_NETWORK=Сетевое со&единение (для сетевых моделей)
STR_ADDITIONAL_UPDTLNCR=Подождите. Выполняется обновление системных файлов.
DRIVERNAME_1=Canon MF4010 Series UFRII LT
