# Generated by Django 6.1.1 on 2026-09-19 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название сайта')),
                ('descriptions', models.TextField(verbose_name='Описание сайта')),
                ('logo', models.ImageField(upload_to='logo')),
                ('phone', models.CharField(max_length=255, verbose_name='Телефон номера')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('locate', models.CharField(max_length=255, verbose_name='адрес')),
                ('locate_url', models.URLField(verbose_name='Ссылка на 2гис')),
            ],
            options={
                'verbose_name': 'Основная настройка',
                'verbose_name_plural': 'Основные настройки',
            },
        ),
    ]
